# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.6
_src_path: gh:algorandfoundation/algokit-python-template
author_email: odoemeneobinna@gmail.com
author_name: Obislok
contract_name: digital_marketplace
deployment_language: python
preset_name: production
project_name: digital_marketplace

